### ISSUE TITLE
Link at the end of MATERIALS - INTRO TO R

### ISSUE THREAD

**Issue by gilienv** [cambiotraining/dataviz-figdesign#3]
I think the last link on this page  (INTRO TO R)needs to go to "STARTING WITH DATA" Section on the Materials.
But it's currently not taking you anywhere - it's not even broken - I think it connects you to the same page - a little upstairs!

**Comment by mvanrongen** [comment]
Hi, can you paste a bit of text as to where this link is? I've looked but I can't find what you are referring to.
