### ISSUE TITLE
Links to add to the general information page

### ISSUE THREAD

**Issue by MDCastle** [cambiotraining/dataviz-figdesign#5]
Can you add a link to Zoom (https://us02web.zoom.us/j/89823349789?pwd=TzVmeDJ0Vm9kOU8yNzFuRFJldE1wZz09).
* we'll be using this for any participants who are self isolating and want to join in and also for participants to share their screen with the presenter in sessions 1 and 6.

Can you add a link to the slack workspace (both the joining and standard URL). They should have all joined beforehand but it's useful in case they forget.
* https://join.slack.com/t/experiencepgl-s9e1967/shared_invite/zt-sgqaena9-K8zMsGmP4PmUEwxXCS7pjw
* https://experiencepgl-s9e1967.slack.com

**Comment by mvanrongen** [comment]
not done because of open access to website
